Repository Automattic/vip-go-ci, pull requests merged in 2021-07, with the labels that each got.

#187 Attempt to reduce GitHub API usage a bit
  README.md
  tests/ApHashesApiScanCommitTest.php
  tests/GitHubPrGenericSupportCommentTest.php
  unittests.ini
Labels: [Type] Bug

#189 Adding function vipgoci_options_get_starting_with()
  options.php
  tests/GitHubPrsImplicatedTest.php
  tests/OptionsGetStartingWithTest.php
Labels: [Type] Enhancement

#191 Fix commit sha used for large files tests
  unittests.ini
Labels: [Status] VIP Auto Approved
