Repository Automattic/vip-go-ci, pull requests merged in 2021-04, with the labels that each got.

#153 Use local git repository to get git diffs
  .vipgoci_options
  README.md
  ap-file-types.php
  ap-hashes-api.php
  ap-nonfunctional-changes.php
  ap-svg-files.php
  auto-approval.php
  defines.php
  git-repo.php
  github-api.php
  main.php
  misc.php
  phpcs-scan.php
  statistics.php
  tests/ApAutoApprovalTest.php
  tests/ApFileTypesTest.php
  tests/GitRepoDiffsFetchTest.php
  tests/GitRepoDiffsFetchUncachedTest.php
  tests/GitVersionTest.php
  tests/MiscGitHubEmojisTest.php
  tests/MiscPatchChangedLinesTest.php
  tests/MiscSanitizePathPrefixTest.php
  tests/StatsRunTimeMeasureShellExecTest.php
  unittests.ini
Labels: [Status] In Progress, [Type] Enhancement

#158 Fix bug with vipgoci_gitrepo_blame_for_file()
  git-repo.php
  phpcs-scan.php
  tests/GitRepoRepoBlameForFileTest.php
  unittests.ini
Labels: [Type] Bug

#161 Update PHP version in the README file
  README.md
Labels: [Status] VIP Auto Approved
